config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :tasks, only: [:index, :new, :create] do
    member do
      patch :mark_as_done
    end
  end
  get "profile", to: 'dashboard#profile', as: :profile
  get "review", to: 'nextday#review', as: :review
end



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  attr_accessor :habit

  scope :regular_tasks, -> { where(days: nil) }
  scope :habits, -> { where.not(days: nil) }
  scope :done, -> { where(mark_as_done: true) }
  scope :not_done, -> { where(mark_as_done: false) }

  belongs_to :user

  validates :name, presence: true

  before_create :set_default_start_at
  def set_default_start_at
    return if start_at.present?

    self.start_at = Date.today
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tasks, dependent: :destroy

  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

    # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)|(^dashboard$)|(^nextday$)/
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def profile
    @user = current_user
  end
end

app/controllers/nextday_controller.rb
class NextdayController < ApplicationController
  def review

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = policy_scope(Task)
    @user = current_user
    @username = @user.username
    @total = nb_total_tasks
    @nb_habits_not_done = Task.habits.not_done.count
    @nb_tasks_not_done = Task.regular_tasks.not_done.count
    @estimated_time = estimated_time
    @regular_tasks = regular_tasks
  end

  def new
    @task = Task.new
    authorize @task
  end

  def create
    @task = Task.new(task_params)
    @task.user = current_user
    authorize @task
    if @task.save
      redirect_to tasks_path
    else
      render :new
    end
  end

  def mark_as_done
    @task = Task.find(params[:id])
    authorize @task
    @task.mark_as_done = !@task.mark_as_done
    @task.save
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:name, :details, :priority, :start_at, :duration, days:[])
  end

  def regular_tasks
    @tasks.where(days: nil)
  end

  def habits
    @tasks.where.not(days: nil)
  end

  def nb_total_tasks
    @tasks.count
  end

  def nb_tasks
    regular_tasks.count
  end

  def nb_habits
    habits.count
  end

  def estimated_time
    t = 0
    @tasks.not_done.each do |task|
      t += task.duration unless task.duration.nil?
    end
    return "00:00" if t.zero?

    if t >= 60
      h = t.modulo(60)
      mn = t - (h * 60)
      return "#{h}:00" if mn.zero?

      return "#{h}:#{mn}"
    end
    return "00:#{t}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def better_time(object)
    object.strftime("%A %-d %B %Y")
  end
end

app/views/dashboard/profile.html.erb
<div class="container">
  <div class="">
    <h3> Hey, <%=@user.username%></h3>
    <div>
      <%= link_to "Edit my profile", edit_user_registration_path(current_user), class: "btn btn-ghost" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Neatt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body class="<%= params[:controller]%>-<%= params[:action]%>">
    <% if  params[:action] != "home" %>

      <%= render 'shared/navbartop' %>
      <%= render 'shared/flashes' %>
    <% end %>

    <%= yield %>
    <% if params[:action] == "profile" %>
      <%= render 'shared/navbartwo' %>
    <% elsif params[:action] != "home" %>
      <%= render 'shared/navbar' %>
    <% end %>
  </body>
</html>

app/views/nextday/review.html.erb
<h1>Review time!</h1>

app/views/pages/home.html.erb
<div class="container text-center home-container size-min-screen">
  <div class="">
    <h1>Neatt</h1>
    <h2>Free to plan your life day by day </h2>
    <%= link_to "Go to my tasks", tasks_path, class: "btn btn-ghost mt-5"%>
    <%= link_to "Log in", new_user_session_path, class: "btn btn-ghost mt-5"%>
    <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-ghost mt-5" %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="nav-centrage fixed-bottom">
  <div>
    <%= link_to profile_path do %>
      <i class="fas fa-chart-area bloc-icon icon-color"></i>
    <% end %>
  </div>
  <div class="add-button-navbar">
    <%= link_to new_user_registration_path, class: "btn add-button" do %>
      <i class="fas fa-plus "></i>
    <% end %>
  </div>
  <div>
    <%= link_to "Next day", review_path, class: "text-nav"%>
  </div>
</div>

app/views/shared/_navbartop.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="nav-item dropdown">
    <a class="fas fa-cog bloc-icon icon-color " href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
      <% if user_signed_in? %>
      <li class="nav-item active">
        <%= link_to "Dashboard", profile_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      </li>
    <% end %>
    </div>
  </div>

  <div class="text-nav-top">
    <%= better_time(Date.today) %>
  </div>

  <div>
    <%= link_to new_user_registration_path do %>
      <i class="fas fa-search bloc-icon icon-color "></i>
    <% end %>
  </div>
</div>

app/views/shared/_navbartwo.html.erb
<div class="nav-centrage fixed-bottom">
  <div>
    <%= link_to tasks_path do %>
      <i class="fas fa-home bloc-icon icon-color"></i>
    <% end %>
  </div>
  <div class="add-button-navbar">
    <%= link_to new_user_registration_path, class: "btn add-button" do %>
      <i class="fas fa-plus "></i>
    <% end %>
  </div>
  <div>
    <%= link_to "Next day", review_path, class: "text-nav"%>
  </div>
</div>

app/views/tasks/_estimated_time.html.erb
<div class="estimated_time d-flex justify-content-center">
  <p>Est. time: </p>
  <i class="fas fa-clock ml-2 mr-1"></i>
  <p> <%=@estimated_time%></p>
</div>

app/views/tasks/_hey.html.erb
<div class="hey d-flex justify-content-center">
  <p class="text-center">Hey <%=@username%>, you have <strong><%=pluralize @nb_tasks_not_done, 'task'%></strong> and <br>
  <strong><%=pluralize @nb_habits_not_done, 'habit'%></strong> remaining today.</p>
</div>

app/views/tasks/index.html.erb
<%= render "hey" %>
<%= render "estimated_time" %>

<h4 class="index">TOP PRIORITY</h3>
<ul>
  <div class="list-container">
    <% @tasks.where(priority: true).not_done.each do |task|%>
      <%= simple_form_for task,
          url: mark_as_done_task_path(task),
          namespace: "task_#{task.id}",
          html: {
            class: "form-inline",
            data: { controller: 'check-task' }
          } do |f|  %>
        <div class="task-box task-list">
          <%= f.input :mark_as_done, as: :boolean, label: task.name, input_html: { 'data-action': 'change->check-task#submit'} %>
        </div>
        <%= f.submit "ok", class: "d-none", 'data-check-task-target': 'submitBtn' %>
      <% end %>
    <% end %>
    <% @tasks.where(priority: true).done.each do |task|%>
      <%= simple_form_for task,
          url: mark_as_done_task_path(task),
          namespace: "task_#{task.id}",
          html: {
            class: "form-inline",
            data: { controller: 'check-task' }
          } do |f|  %>
        <div class="task-box task-list">
          <%= f.input :mark_as_done, as: :boolean, label: task.name, input_html: { 'data-action': 'change->check-task#submit'} %>
        </div>
        <%= f.submit "ok", class: "d-none", 'data-check-task-target': 'submitBtn' %>
      <% end %>
    <% end %>
  </div>
</ul>

<h4 class="index">TASKS</h3>
<ul>
  <div class="list-container">
    <% @tasks.where(priority: false).not_done.each do |task|%>
      <%= simple_form_for task,
          url: mark_as_done_task_path(task),
          namespace: "task_#{task.id}",
          html: {
            class: "form-inline",
            data: { controller: 'check-task' }
          } do |f|  %>
        <div class="task-box task-list">
          <%= f.input :mark_as_done, as: :boolean, label: task.name, input_html: { 'data-action': 'change->check-task#submit'} %>
        </div>
        <%= f.submit "ok", class: "d-none", 'data-check-task-target': 'submitBtn' %>
      <% end %>
    <% end %>
    <% @tasks.where(priority: false).done.each do |task|%>
      <%= simple_form_for task,
          url: mark_as_done_task_path(task),
          namespace: "task_#{task.id}",
          html: {
            class: "form-inline",
            data: { controller: 'check-task' }
          } do |f|  %>
        <div class="task-box task-list">
          <%= f.input :mark_as_done, as: :boolean, label: task.name, input_html: { 'data-action': 'change->check-task#submit'} %>
        </div>
        <%= f.submit "ok", class: "d-none", 'data-check-task-target': 'submitBtn' %>
      <% end %>
    <% end %>
  </div>
</ul>

app/views/tasks/new.html.erb
<div class="container">
  <h1>New Task</h1>
  <%= simple_form_for(@task) do |f| %>
    <%= f.input :name %>
    <%= f.input :details %>
    <%= f.input :start_at, as: :string,
                required: false,
                wrapper_html: { data: {controller: "task-calendar"} }, input_html: { data: {task_calendar_target:"date", action:"click->task-calendar#showCalendar"} } %>
    <%= f.input :priority, input_html: { class: "toggle" } %>
    <%= f.input :duration, placeholder: "minutes", input_html: { min: '0', step: '15' } %>
    <%= f.input :habit, as: :boolean, input_html: { class: "toggle" }  %>
    <%= f.input :days,
                collection: Date::DAYNAMES.map { |day_name| [day_name, Date::DAYNAMES.index(day_name)] },
                label: "",
                as: :check_boxes,
                include_hidden: false,
                input_html: { class: "tag-selector" },
                item_wrapper_class: 'tag-item'
    %>
    <%= f.submit class: "btn-ghost" %>
  <% end %>
</div>